# Welcome to Jekyll!
#
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Matt Stibbs
email: m.stibbs@nhs.net
description: Integrated & Emergency Care Technical Standards.


# Build settings
markdown: kramdown
theme: minima
permalink: /:path/:basename

# Default Settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "content_page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

# Collections
collections:
  integrated-urgent-care-technical-standards:
    output: true
    title: Integrated Urgent Care Technical Standards
    permalink: /:collection/:title.html

  nhs111-imt-standards:
    output: true
    title: NHS111 IM&T Standards
    permalink: /:collection/:title.html
